#pragma config(Motor,  port4,           leftFront,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           rightFront,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           leftBack,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           rightBack,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
//move forward
while(1==1)
{
motor[rightFront]  = vexRT[Ch3] - vexRT[Ch4] + vexRT[Ch1];
motor[rightBack] = vexRT[Ch3] + vexRT[Ch4] + vexRT[Ch1];
motor[leftFront] = -vexRT[Ch3] - vexRT[Ch4] + vexRT[Ch1];
motor[leftBack] = -vexRT[Ch3] + vexRT[Ch4]  + vexRT[Ch1];
}

// Left joystick movement
// Right joystick point turn
}
// vexRT[Ch1] right joystick side x-axis
// vexRT[Ch2] right joystick side x-axis
